import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rward</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Rward</h1>

        <div className={styles.grid}>
          <Link href="/dashboard">
            <a className={styles.card}>
              <h2>Get key &rarr;</h2>
              <p>Add token rewards to your app</p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
}
