import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rward</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>rward</h1>

        <div className={styles.grid}>
          <Link href="/dashboard">
            <a className="mt-10 block px-5 py-3 text-sm font-medium text-white transition bg-indigo-600 rounded-lg hover:bg-indigo-700 focus:outline-none focus:ring">
              {"Get Free API Key ->"}
            </a>
          </Link>
        </div>
        <div className="p-4 m-5 border border-gray-200 rounded">
          <p>{"Install Our SDK"}</p>
          <p className={styles.code}>{"yarn add @rward.xyz/sdk"}</p>
        </div>
      </main>
      <Footer />
    </div>
  );
}
